# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Hardcore), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker
Telegram=1
chrome-www.facebook.com__-Default=1
com.mitchellh.ghostty=1
