[Macro/0]
# Key
Key=~gt
# Value
Value="giải thích"

[Macro/1]
# Key
Key=gt
# Value
Value="giải thích"

[Macro/2]
# Key
Key=~hd
# Value
Value="hướng dẫn"

[Macro/3]
# Key
Key=hd
# Value
Value="hướng dẫn"

[Macro/4]
# Key
Key=~hdsd
# Value
Value="hướng dẫn sử dụng"

[Macro/5]
# Key
Key=hdsd
# Value
Value="hướng dẫn sử dụng"

