-- Generated by user.trackpad-gestures. Changes will be overwritten.
local function relative_workspace_gesture(target, axis)
  local distance = 0
  local triggered = false

  local function consume(event)
    if triggered then return end
    local delta = axis == "x" and event.delta.x or event.delta.y
    distance = distance + math.abs(delta)
    if distance >= 25 then
      triggered = true
      hl.dispatch(hl.dsp.focus({ workspace = target }))
    end
  end

  return {
    start = function(event)
      distance = 0
      triggered = false
      consume(event)
    end,
    update = consume,
    finish = function()
      distance = 0
      triggered = false
    end,
  }
end

local function active_layout()
  local ok, ws = pcall(hl.get_active_workspace)
  return (ok and ws and (ws.tiled_layout or ws.tiledLayout)) or "dwindle"
end

local function fit_all_gesture()
  pcall(function()
    if active_layout() == "scrolling" then
      hl.dispatch(hl.dsp.layout("fit all"))
    else
      local win = hl.get_active_window()
      if win and (win.fullscreen == 1 or win.fullscreen == true) then
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 0, client = 0 }))
      end
    end
  end)
end

local function fit_active_gesture()
  pcall(function()
    if active_layout() == "scrolling" then
      hl.dispatch(hl.dsp.layout("fit active"))
    else
      local win = hl.get_active_window()
      if win and (win.fullscreen == 1 or win.fullscreen == true) then
        hl.dispatch(hl.dsp.window.fullscreen_state({ internal = 0, client = 0 }))
      else
        hl.dispatch(hl.dsp.window.bring_to_top())
      end
    end
  end)
end
hl.config({ input = { touchpad = { clickfinger_behavior = true, tap_button_map = "lrm" } } })
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 3, direction = "up", action = { start = fit_all_gesture } })
hl.gesture({ fingers = 3, direction = "down", action = { start = fit_active_gesture } })
hl.gesture({ fingers = 4, direction = "left", action = { start = function() hl.exec_cmd("omarchy-brightness-display 5%-") end } })
hl.gesture({ fingers = 4, direction = "right", action = { start = function() hl.exec_cmd("omarchy-brightness-display +5%") end } })
hl.gesture({ fingers = 4, direction = "up", action = { start = function() hl.exec_cmd("omarchy-audio-output-volume raise") end } })
hl.gesture({ fingers = 4, direction = "down", action = { start = function() hl.exec_cmd("omarchy-audio-output-volume lower") end } })
